# hugo汇编时需要忽略的文件与文件夹
ignoreFiles = [".Rmd$", ".Rmarkdown$", "_files$", "_cache$"]
# 网站根目录，可以是网址
baseURL = "https://wly.supernum.tech/"
# 主界面语言，与i18n文件夹对应
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
# 网站标题
title = "wly's notebook"
# 主页面每页显示多少条post
paginate = 5
# 使用emoji
enableEmoji = true

# post在public文件夹中的放置路径
[permalinks]
  post = "/:year/:month/:slug/"

# post标签、分类、归档路径
[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

# 作者信息
[author]
  name = "wly"
  bio = "令凤鸟飞腾兮，继之以昼夜"
  job = "数据分析师"
  location = "中国 上海"
  # 当 Gravatar email 为空时, 作者头像
  picture = "https://i.postimg.cc/nhmB7j7T/image.png"

# 侧边栏菜单
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-bookmark\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/page/about"

[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/supernum163"
[[menu.links]]
  weight = 2
  identifier = "email"
  name = "Email"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-at\"></i>"
  url = "mailto:supernum@163.com"
[[menu.links]]
  weight = 2
  identifier = "donate"
  name = "打赏"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rmb\"></i>"
  url = "/page/donate"

[[menu.misc]]
  weight = 1
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
  # 侧边栏大小，可以为1至6
  sidebarBehavior = 1
  # 日期格式
  dateFormat = "2006-01-02"
  # 网站背景，修改为底色比较好
  cover = "#171314"

  # 是否插入Math.js, 在post的"math"中覆盖此设置
  math = false
  # 当用户阅读post时，隐藏侧边栏
  clearReading = true
  # 互换post底部“上一篇”与“下一篇”,“上一页”与“下一页”
  # swapPaginator = true
  # post归类标准: `categories = ["foo", "bar"]` 将post归类于 "foo"下层的"bar"中，设置为false则不能进行归类
  hierarchicalCategories = true
  # 当post的meta中含有gallery信息时，在页面底部展示imageGallery
  imageGallery = true

  # 是否显示post展示图
  thumbnailImage = true
  # post展示图默认摆放位置， 可以为"right", "left", "bottom", 在post的"thumbnailImagePosition"中覆盖此设置
  thumbnailImagePosition = "right"
  # 将post中的第一张图片作为post展示图，在post的"autoThumbnailImage"中覆盖此设置
  autoThumbnailImage = true

  # 网站favicon
  favicon = "img/favicon.ico"
  # 全局关键字，在meta信息中
  keywords = ["wly的博客", "supernum"]
  # 网站默认description，在meta信息中
  description = "Hugo tranquilpeak theme demo"

  # 加入自定义CSS
  # [[params.customCSS]]
  #   href = "css/show-url.css"

  # 加入自定义js
  # [[params.customJS]]
  #   src = "http://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"
    
  # 分享链接，在每个post页面底部
  [[params.sharingOptions]]
    name = "新浪微博"
    icon = "fa-weibo"
    url = "http://service.weibo.com/share/share.php?title=title&url=%s&source=bookmark#_loginLayer_1551323382531"

  [[params.sharingOptions]]
    name = "QQ空间"
    icon = "fa-qq"
    url = "http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=%s"

  # 在post右上角对象与链接,默认是用户头像
  [params.header.rightLink]
    url = "/#about"
    class = ""
    icon = ""
    # url = "/#search"
    # icon = "search"
    # class = "st-search-show-outputs"

  # 在侧边栏中加入关于页面
  [params.sidebar.profile]
    url = "/#about"

  # 修改修改所有权声明中的作者
  [params.footer]
    copyright = "<a href=\"https://github.com/supernum163\">supernum</a>"
     
  # gitment评论系统信息
  [params.gitment]
    enable = true
    githubID = "supernum163"
    repo = "wly"
    ClientID = "40f2576aa2a372d81a1a"
    ClientSecret = "c7f5edfb420146da2eed5a09576aaea56f402d30"

  # algolia站内搜索系统
  #[params.algolia]
  #  enable = true
  #  appId = ""
  #  apiKey = ""
  #  indexName = ""
