---
title: "随手记"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# docker

## 列出所有image
docker image ls

## 列出所有container
docker container ls -a

## 制作image，需要有dockerfile
docker build --t imageName .

## 启动image，交互式
docker run -it friendlyhello /bin/bash

## 启动image，将image的80端口映射到本地4000
docker run -p 4000:80 friendlyhello

## 命名image
docker tag imageID imageName

## 上传image
docker tag image username/repository:tag
docker push username/repository:tag

## 删除image
docker image rm -f imageName

## 删除container
docker container rm containerID
## 删除多个container
docker rm $(docker container ls -f "status=exited" -q)
## 删除全部container
docker rm $(docker container ls -aq)

## save/load image
docker save imageName > targetName.tar
docker load < targetName.tar

## export/import container
docker export containerID > targetName.tar
docker import targetName.tar imageName



# shiny-server 

## 默认的配置文件
/opt/shiny-server/config/default.config  

## 实际的配置文件
/etc/shiny-server/shiny-server.conf  

## session
```
@uploadEnd @uploadieFinish @uploadInit 
cache clientData allowReconnect createBookmarkObservers cycleStartAction 
clone close closed decrementBusyCount 
defineOutput dispatch doBookmark downloads exportTestValues 
files fileUrl flushOutput freezeValue getBookmarkExclude 
getCurrentOutputInfo getTestSnapshotUrl groups handleRequest 
incrementBusyCount initialize input isClosed isEnded makeScope 
manageHiddenOutputs manageInputs ns 
onBookmark onBookmarked onEnded onFlush onFlushed onInputReceived onRestore onRestored onSessionEnded 
output outputOptions progressStack reactlog registerDataObj registerDownload 
reload request requestFlush resetBrush restoreContext rootScope saveFileUrl 
sendBinaryMessage sendChangeTabVisibility sendCustomMessage sendInputMessage sendInsertTab sendInsertUI sendModal 
sendNotification sendProgress sendRemoveTab sendRemoveUI 
session setBookmarkExclude setShowcase 
showProgress singletons startTiming token unhandledError updateQueryString user userData wsClosed
```



# DBI连接数据库

```
conn <- dbConnect(drv = odbc::odbc(), dsn = "mssql", uid = 'wly', pwd = 'abc@123', dbname = "dataChche")
conn <- dbConnect(drv = RMySQL::q(), host = "192.168.5.12", port = "1433", uid = 'wly', pwd = 'abc@123', dbname = "dataChche")
conn <- dbConnect(drv = RSQLite::SQLite(), dbname = 'test.db')
```



# 扩容虚拟机

## 查看virtualBox虚拟机磁盘信息
D:\virtualBox\VBoxManage showhdinfo ubuntu-18.04.1-desktop-amd64.vdi

## 扩容virtualBox虚拟机磁盘空间
D:\virtualBox\VBoxManage modifyhd ubuntu-18.04.1-desktop-amd64.vdi --resize 20480
D:\virtualBox\VBoxManage modifymedium ubuntu-18.04.1-desktop-amd64.vdi --resize 20480




# linux查找递归某个文件夹的那些文件包含关键字
grep -rn 关键字 *
grep -rlc 关键字 *

# linux建立文件与应用程序关联
在**/etc/gnome/defaults.list** 中添加一行**application/x-sqlite3=sqlitestudio.desktop**

# linux 建立桌面快捷方式
- linux默认桌面图标存放位置*/usr/share/applications/*  
- linux默认用户可执行程序存放位置*/usr/bin/*  
在**usr/share/applications**中添加一个**sqlitestudio.desktop**文件，内容如下
```{bash eval=FALSE, include=FALSE}
[Desktop Entry]
Type=Application
Version=3.2.1
Name=sqlitestudio
Comment=sqlitestudio.desktop
Icon=/opt/SQLiteStudio/app_icon/sqlitestudio.png
Exec=/opt/SQLiteStudio/sqlitestudio
Terminal=false
```

- 右键查看sqlitestudio.desktop文件属性，给其赋可执行权限  



# 使用smb协议共享文件夹

注意斜杠与反斜杠

## ubuntu文件夹共享给windows
右击任意ubuntu文件夹，在属性中选择**本地网络共享**，勾选**共享此目录**
在window资源管理器中以**\\主机名\共享文件夹名**的形式访问共享文件夹

## windows文件夹共享给ubuntu
右击任意windows文件夹，在**共享**中将其共享给某个用户
在ubuntu文件资源管理其中选择**其它位置**，在**连接到服务器**中以**smb://ip地址/共享文件夹名**的形式访问共享文件夹



# 设置共享wifi
```
netsh wlan set hostednetwork mode=allow ssid=Nathan_5G key=1234567890
netsh wlan start hostednetwork
在网络适配器界面将本地连接共享给无线连接
netsh wlan stop hostednetwork
```


# ubuntu安装mysql
```
sudo apt install mysql-server  mysql-client  
```

## 创建一般用户
```
create user wly identified by password("wly")
```

## 修改用户密码
```
set password for root@localhost = password('root')
```

## 给用户赋权
```
#给用户cacti赋予所有库的所有权限
GRANT ALL PRIVILEGES ON *.* TO 'cacti'@'%' IDENTIFIED BY 'cacti' WITH GRANT OPTION;
#收回权限(不包含赋权权限)
REVOKE ALL PRIVILEGES ON *.* FROM cacti;
REVOKE ALL PRIVILEGES ON cacti.* FROM cacti;
#收回赋权权限
REVOKE GRANT OPTION ON *.* FROM cacti;
```

## 重新载入赋权表
```
FLUSH PRIVILEGES;
```

## 汉化mysql-workbench
修改**/usr/share/mysql-workbench/data**中的**.xml**文件




